# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Yet another blog
email: alex.vakhitov@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Привет, меня зовут Алексей Вахитов, занимаюсь разработкой на Python и Golang.
  Здесь я веду свой блог, в основном пишу о разработке на Python, но могу написать и что-то другое.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://ru.vahaah.guru" # the base hostname & protocol for your site, e.g. http://example.com

# theme

twitter_username: vahaah
github_username:  vahaah
instagram_username: vahaah
telegram_username: vahaah

minima:
  date_format: "%d.%m.%Y"

# Build settings
lang: ru
permalink: /:year/:month/:day/:title:output_ext
paginate: 10
paginate_path: "p/:num"
show_excerpts: true
excerpt_separator: <!--more-->

markdown: kramdown
highlighter: rouge
redcarpet:
  extensions:
    - no_intra_emphasis
    - fenced_code_blocks
    - autolink
    - tables
    - with_toc_data

plugins:
  - jekyll-feed
  - jekyll-typogrify
  - jekyll-paginate
  - jekyll-bits
  - jekyll-sitemap
  - jekyll-redirect-from

exclude:
  - README.md
  - LICENSE.txt
  - Gemfile.lock
  - Gemfile
  - Rakefile
  - node_modules

# see https://github.com/alfanick/jekyll-related-posts
related:
  max_count: 5
  min_score: 0.1
  accuracy: 0.75

# jekyll-feed
rss: RSS Feed
feed:
  title: ru.vahaah.guru
  subtitle: Yet another blog
  path: rss.xml

sass:
  style: compressed
  deploy_style: compressed
  compile_in_place: false

# see https://github.com/pattex/jekyll-tagging
tag_page_layout: tag-index
tag_page_dir: tag

# http://jch.penibelst.de/
compress_html:
  clippings: [div, p, ul, td, h1, h2]
  comments: all
  # endings: all
